### ISSUE TITLE
Bug or confusion with correct serachValue format in ReplaceText( string searchValue,  Func<string, string> regexMatchHandler, ...

### ISSUE THREAD

**Issue by makeProjectGreatAgain** [xceedsoftware/DocX#406] opened 2021-05-17 14:55 UTC
I had bug with `document.ReplaceTextWithText();`, it removed all matches in document.

There is `DocumentSample.ReplaceTextWithText();` function in **Xceed.Words.NET.Examples**
```
document.ReplaceText( "<(.*?)>", DocumentSample.ReplaceFunc, false, RegexOptions.IgnoreCase, new Formatting() { Bold = true, FontColor = System.Drawing.Color.Green } )
;
```
I edited this example and
searchValue = **"<(Date)>"** works ok
searchValue = **"Date"** fails - `findStr` in `ReplaceFunc( string findStr )` is always empty
```
private static string ReplaceFunc( string findStr )
    {
      if( _replacePatterns.ContainsKey( findStr ) )
      {
        return _replacePatterns[ findStr ];
      }
      return findStr;
    }
```
As a result, **It finds all matches** and replace them with an empty string.

This bug reproduced in 1.5.0 - 1.7.1

**Comment by XceedBoucherS** [comment] 2021-05-18 12:47
Hi,
Yes, there is a bug for a specific situation. This is a duplicate of issue https://github.com/xceedsoftware/DocX/issues/401.
The fix is already applied and will be part of v2.0 (v1.9 is skipped).
Thank you.

**Closed by XceedBoucherS** 2021-05-18 12:47 UTC
