### ISSUE TITLE
Wiki Link Doesn't Work

### ISSUE THREAD

**Issue by MattFox1388** [xceedsoftware/DocX#266] opened 2018-08-23 21:58 UTC
Hello, 

I was just trying to find out more information on how to use DocX, but the documentation link gives a 404 error.

**Comment by XceedBoucherS** [comment] 2018-08-24 20:02
Hi,

Thank you for reporting this. 
The link will be fixed.
It should point to https://xceed.com/wp-content/documentation/xceed-document-libraries-for-net/webframe.html#rootWelcome.html

**Closed** 2018-08-28 17:44 UTC

**Comment by txelu** [comment] 2018-09-25 17:02
The link is not working yet, but the issue is closed

**Comment by ronaldhoek** [comment] 2018-09-26 05:50
Just modified the link on the Wiki page (seems I've got write access ... ?)

**Comment by txelu** [comment] 2018-09-26 10:47
It works now. Thanks @ronaldhoek
